version: '3.7'
services:
  # BaseImage
  base:
    build: ./php
    volumes:
      - ./www:/var/www/html
      - ./php/config:/usr/local/etc/php
      - ./apache/log/:/var/log/apache2/
      #- ./apache/config/apache2.conf:/etc/apache2/apache2.conf
      #- ./apache/config/localhost.conf:/etc/apache2/sites-available/localhost.conf
      #- ./apache/config/localhost.conf:/etc/apache2/sites-enabled/localhost.conf
    container_name: base
    ports:
      - "${HTTP_PORT}:80"
  # MySQL
  mysql:
    image: ./mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data-import:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/config/my.cnf:/etc/my.cnf
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  # PHPMA
  phpmyadmin:
    build: ./phpmyadmin
    volumes:
      - ./phpmyadmin/config/config.inc.php:/var/www/html/config.inc.php
    links:
      - mysql
    ports:
      - '${PHPMA_PORT}:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  # Redis
  redis:
    build: ./redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/config/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./redis/log/redis.log:/usr/local/redis/redis.log
    restart: always
    container_name: redis
  # Redis WEB-CLI
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - "${REDIS_WEB_CLI_PORT}:8081"